<a href="https://colab.research.google.com/github/CHIRANJEEVBHATT/Python/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
## crete array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)

In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape((1,5)) ## 1row 5 col

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)

In [ ]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#numpy vector operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element wise addition
print("addition" , arr1+arr2)

#subs
print("substraction", arr1-arr2)

#multi
print("substraction", arr1*arr2)

#div
print("divide", arr1/arr2)

addition [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
substraction [ 10  40  90 160 250]
divide [0.1 0.1 0.1 0.1 0.1]

In [ ]:
#universal function
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]

In [ ]:
#slicing and indexing

arr=np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
print("arr" , arr)

arr [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

In [ ]:
arr[0][0]

np.int64(1)

In [ ]:
arr[1:,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
arr[1:,1:3]

array([[ 6,  7],
       [11, 12]])

In [ ]:
##modify element
arr[0][0] = 100
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]

In [ ]:
#static comcept --- normalization
##data to have mean  = 0 and sd=1

data=np.array([1,2,3,4,5,6,7,8,9,10])
#calculate mean std
mean = np.mean(data)
std = np.std(data)
#noramlize
normalize_data = (data-mean)/std
print("mean", mean)
print("std", std)
print("median" , np.median(data))
print("var" , np.var(data))

print("normalized data" , normalize_data)
print("min", np.min(normalize_data))
print("max", np.max(normalize_data))

mean 5.5
std 2.8722813232690143
median 5.5
var 8.25
normalized data [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
min -1.5666989036012806
max 1.5666989036012806

In [ ]:
#logical oper
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
data[(data>5) & (data<8)]

array([6, 7])

In [ ]:
import pandas as pd

In [ ]:
## series -> store 1 dim data

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
#create series from dict

data={'a':1,'b':2,'c':3,'d':4}
series_dict = pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
d    4
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
#dataframe
## dataframe from dict of list

data={
    'Name':['krish','John','jack'],
    'Age' : [25,56,32],
    'city':['mumbai','texas','ny']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age    city
0  krish   25  mumbai
1   John   56   texas
2   jack   32      ny
<class 'pandas.core.frame.DataFrame'>

In [ ]:
np.array(df)

array([['krish', 25, 'mumbai'],
       ['John', 56, 'texas'],
       ['jack', 32, 'ny']], dtype=object)

In [ ]:
#create df from list of dict

data=[
    {'name':'krish','age':32,'city':'bangalore'},
    {'name':'cb','age':24,'city':'ny'},
    {'name':'arnav','age':32,'city':'dubai'},

]
df=pd.DataFrame(data)
print(df)

    name  age       city
0  krish   32  bangalore
1     cb   24         ny
2  arnav   32      dubai

In [ ]:
df=pd.read_csv('/sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
df.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
### access data from df
data

[{'name': 'krish', 'age': 32, 'city': 'bangalore'},
 {'name': 'cb', 'age': 24, 'city': 'ny'},
 {'name': 'arnav', 'age': 32, 'city': 'dubai'}]

In [ ]:
df['name']

0    krish
1       cb
2    arnav
Name: name, dtype: object

In [ ]:
df.loc[0]

name        krish
age            32
city    bangalore
Name: 0, dtype: object

In [ ]:
df.iloc[0]

name        krish
age            32
city    bangalore
Name: 0, dtype: object

In [ ]:
df.iloc[0][0]

/tmp/ipykernel_16466/2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'krish'

In [ ]:
#accessing specific element
df

    name  age       city
0  krish   32  bangalore
1     cb   24         ny
2  arnav   32      dubai

In [ ]:
df.at[0,'age']

np.int64(32)

In [ ]:
#using iat
df.iat[2,2]

'dubai'

In [ ]:
#data manipulation of df
df['salary']=[50000,10000000,60000]
df

    name  age       city    salary
0  krish   32  bangalore     50000
1     cb   24         ny  10000000
2  arnav   32      dubai     60000

In [ ]:
#remove col #### temp oper for it use ## implace
df.drop('salary',axis=1)

    name  age       city
0  krish   32  bangalore
1     cb   24         ny
2  arnav   32      dubai

In [ ]:
df

    name  age       city    salary
0  krish   32  bangalore     50000
1     cb   24         ny  10000000
2  arnav   32      dubai     60000

In [ ]:
df.drop('salary',axis=1,inplace=True)

In [ ]:
df

    name  age       city
0  krish   32  bangalore
1     cb   24         ny
2  arnav   32      dubai

In [ ]:
## add age to col
df['age']=df['age']+1
df

    name  age       city
0  krish   33  bangalore
1     cb   25         ny
2  arnav   33      dubai

In [ ]:
df=pd.read_csv('/sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
print("statics" , df.describe())

statics        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
print("datatype" , df.dtypes)

datatype Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object